  name: build push and deploy image

  on:
    push:
      branches: [main]
    pull_request:
      branches: [main]
  
  env:
    AWS_REGION: us-east-1
    AWS_ROLE: ${{ secrets.AWS_ACTION_ROLE }}
  

  jobs:
    build:
      runs-on: ubuntu-latest #github runner
      steps:
        - name: clone repo
          uses: actions/checkout@
        - name: Aws creds config
          uses: aws-actions/config-aws-credentials@v4
          with:
            role-to-assume: ${{env.AWS_ROLE}}   # OIDC
            aws-region: ${{ env.AWS_REGION}}
        - name: Login to ecr
          uses:  aws-actions/amazon-ecr-login@v1